export const projectsData = (t) => [
    {
      title: t("projects_section.title_v1"),
      description: t("projects_section.desc_v1"),
      technologies: [
        "Javascript",
        "React",
        "Express",
        "Nodejs",
        "Tailwind CSS",
        "Dotenv",
        "Git",
        "Twilio",
        "Vercel",
      ],
      icons: ["mobile", "tablet", "desktop", "dark", "translate"],
      liveUrl: "https://www.hectormartil.dev/",
      repoUrl: "https://github.com/hembi12/my-portfolio",
    },
    {
      title: t("projects_section.title_wedding"),
      description: t("projects_section.desc_wedding"),
      technologies: [
        "Javascript",
        "React",
        "Next.js",
        "Nodejs",
        "Tailwind CSS",
        "Dotenv",
        "Git",
        "Formspree",
        "Vercel",
      ],
      icons: ["mobile", "tablet", "desktop"],
      liveUrl: "https://www.bodahectormichelle.info/",
      repoUrl: "https://github.com/hembi12/wedding",
    },
    {
      title: t("projects_section.title_v2"),
      description: t("projects_section.desc_v2"),
      technologies: [
        "Javascript",
        "React",
        "Vite",
        "Nodejs",
        "Tailwind CSS",
        "Dotenv",
        "Git",
        "Render",
        "Vercel",
      ],
      icons: ["mobile", "tablet", "desktop", "dark", "translate"],
      liveUrl: "https://tiendadigital.store",
      repoUrl: "https://github.com/hembi12/portfolio_v2",
    },
    {
      title: t("projects_section.title_birthday"),
      description: t("projects_section.desc_birthday"),
      technologies: [
        "Javascript",
        "HTML",
        "CSS",
        "Nodejs",
        "Bootstrap",
        "Dotenv",
        "Git",
        "Firebase",
      ],
      icons: ["mobile", "tablet", "desktop", "dark"],
      liveUrl: "https://tareaspro.com",
      repoUrl: "https://github.com/usuario/tareaspro",
    },
  ];